cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', shopping_cart_view, name='shopping_cart_view'),
    path('add/<int:pk>', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:pk>', remove_from_cart_view, name='remove_from_cart_view'),
    path('emptying_the_cart', emptying_all_of_the_products_from_the_cart, name='emptying_the_cart')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls'), name='homepage'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('shopping-cart/', include('cart.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # rosetta
    path('rosetta/', include('rosetta.urls'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms


class AddToCartProductForm(forms.Form):

    def __init__(self, *args, **kwargs):
        product_stock = kwargs.pop('product_stock')
        super(AddToCartProductForm, self).__init__(*args, **kwargs)
        QUANTITY_CHOICES = [(i, str(i)) for i in range(1, int(product_stock) + 1)]
        self.fields['inplace'] = forms.BooleanField(required=False, widget=forms.HiddenInput)
        self.fields['quantity'] = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int, required=True)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from product.models import Product
from .cart import ShoppingCart
from .forms import AddToCartProductForm
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.http import Http404


def shopping_cart_view(request):
    shopping_cart = ShoppingCart(request)
    for item in shopping_cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial={
            'quantity': item['quantity'],
            'inplace': True,
        }, product_stock=item['product_obj'].product_price)
    # dic for context
    dic = {
        'shopping_cart': shopping_cart,
    }
    return render(request, 'cart/shopping_cart.html', dic)


@require_POST
def add_to_cart_view(request, pk):
    shopping_cart = ShoppingCart(request)
    product = get_object_or_404(Product.product_manager, id=pk)
    # rendering our form
    form = AddToCartProductForm(request.POST, product_stock=product.number_of_products)
    if request.method == 'POST':
        if form.is_valid():
            # clean data:  Django creates an attribute called cleaned_data ,
            # a dictionary which contains cleaned data only from the fields which have passed the validation tests.
            cleaned_data = form.cleaned_data
            quantity = cleaned_data['quantity']
            shopping_cart.add_to_cart(product, quantity, replace_current_quantity=cleaned_data['inplace'])
            if cleaned_data['inplace']:
                messages.success(request, 'product quantity updated successfully')
            elif not cleaned_data['inplace']:
                messages.success(request, 'this product added to your cart successfully')
            # check if quantity of product is bigger than a number of products in database
        return redirect('cart:shopping_cart_view')


def remove_from_cart_view(request, pk):
    shopping_cart = ShoppingCart(request)
    product = get_object_or_404(Product.product_manager, id=pk)
    shopping_cart.delete_from_cart(product)
    messages.warning(request, 'this product deleted from your cart')
    return redirect('product_detail_view', pk=pk)


def emptying_all_of_the_products_from_the_cart(request):
    shopping_cart = ShoppingCart(request)
    shopping_cart.emptying_the_cart()
    return redirect('products_list_view')

cart/templates/cart/shopping_cart.html
{% extends '_base.html' %}
{% load i18n %}
{% block content %}
{% load english_to_persian_translate_tags %}
{% load humanize %}


{% trans 'CART' as main_header %}
{% include 'top_header.html' with main_header='CART' %}

<!-- Main Content Wrapper Start -->
<div class="main-content-wrapper">
    <div class="page-content-inner ptb--80">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-md--50">
                    <div class="row no-gutters">
                        <div class="col-12">
                            <div class="table-content table-responsive">
                                <table class="table text-center">
                                    <thead>
                                        <tr>
                                            <th>&nbsp;</th>
                                            <th>عکس محصول</th>
                                            <th>نام محصول</th>
                                            <th>قیمت</th>
                                            <th>مقدار</th>
                                            <th>مجموع</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in shopping_cart %}
                                            <tr>
                                                <td class="product-remove text-left"><a
                                                        href="{% url 'cart:remove_from_cart_view' item.product_obj.id %}"><i
                                                        class="flaticon flaticon-cross"></i></a></td>
                                                <td class="product-thumbnail text-left">
                                                    <img src="{{ item.product_obj.product_cover.url }}" alt="Product Thumnail">
                                                </td><td class="product-name">
                                                    <h3>
                                                        <a href="{% url 'product_detail_view' item.product_obj.id %}">
                                                            {{ item.product_obj.product_title }}</a>
                                                    </h3>
                                                </td>
                                                <td class="product-price">
                                                    <span class="product-price-wrapper">
                                                        <span class="money">{{ item.product_obj.product_price|intcomma:False|translate_number }} {% trans "$" %}</span>
                                                    </span>
                                                </td>
                                                <td class="product-quantity">
                                                    <form method="post" action="{% url 'cart:add_to_cart' item.product_obj.id %}">
                                                        {% csrf_token %}
                                                         <div class="quantity">
                                                            <input type="number"
                                                                   class="quantity-input"
                                                                   name="quantity"
                                                                   id="qty-1"
                                                                   min="1"
                                                                   value="{{ item.quantity}}"
                                                                   max="{{ item.product_obj.number_of_products|translate_number}}"
                                                            >
                                                            {{ item.product_update_quantity_form.inplace}}
                                                             <button type="submit">{% trans 'Update' %}</button>
                                                        </div>
                                                    </form>
                                                </td>
                                                <td class="product-total-price">
                                                    <span class="product-price-wrapper">
                                                        <span class="money">{{ item.total_price|intcomma:False|translate_number }} {% trans "$" %}</span>
                                                    </span>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="row no-gutters border-top pt--20 mt--20">
                        <div class="col-sm-6 text-sm-right">
                            <a href="{% url 'cart:emptying_the_cart' %}" class="cart-form__btn">خالی کردن سبد خرید</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart-collaterals">
                        <div class="cart-totals">
                            <h5 class="font-size-14 font-bold mb--15">مجموع</h5>
                            <div class="cart-calculator">
                                <div class="cart-calculator__item">
                                    <div class="cart-calculator__item--head">
                                        <span>مجموع</span>
                                    </div>
                                    <div class="cart-calculator__item--value">
                                        <span>{{ shopping_cart.get_total_price|intcomma:False|translate_number }} {% trans "$" %}</span>
                                    </div>
                                </div>
                                <div class="cart-calculator__item order-total">
                                    <div class="cart-calculator__item--head">
                                        <span>جمع کل</span>
                                    </div>
                                    <div class="cart-calculator__item--value">
                                        <span class="product-price-wrapper">
                                            <span class="money">{{ shopping_cart.get_total_price|intcomma:False|translate_number }} {% trans "$" %}</span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="checkout.html" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                            ثبت سفارش
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Content Wrapper Start -->
{% endblock content %}

cart/templates/cart/shopping_cart_sidebar.html
{% load i18n %}
{% load english_to_persian_translate_tags %}
{% load humanize %}

<aside class="mini-cart" id="miniCart">
        <div class="mini-cart-wrapper">
            <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="mini-cart-inner">
                <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">{% trans 'shopping cart' %}</h3>
                <div class="mini-cart__content">
                    <ul class="mini-cart__list text-right">
                        {% for item in shopping_cart %}
                            <li class="mini-cart__product d-flex justify-content-between">
                            <div class="mini-cart__product__image">
                                <a href="{% url 'product_detail_view' item.product_obj.id %}">
                                    <img src="{{ item.product_obj.product_cover.url }}" alt="products">
                                </a>
                            </div>
                            <div class="mini-cart__product__content pt-2">
                                <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                    <a href="#">{{ item.product_obj.product_title }}</a>
                                    <a href="{% url 'cart:remove_from_cart_view' item.product_obj.id %}" class="">
                                        &#10060;
                                    </a>
                                </span>
                                <span class="mini-cart__product__quantity">
                                    <span>{{ item.product_obj.product_price|intcomma:False|translate_number }} {% trans '$' %}</span> &#215;
                                    <span>{{ item.quantity|intcomma:False|translate_number }}</span>
                                </span>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="mini-cart__total">
                        <span>جمع کل</span>
                        <span class="ammount">{{ item.total_price|intcomma:False|translate_number}}</span>
                    </div>
                    <div class="mini-cart__buttons">
                        <a href="{% url 'cart:shopping_cart_view' %}" class="btn btn-fullwidth btn-bg-sand mb--20">{% trans 'Checkout' %}</a>
                        <a href="checkout.html" class="btn btn-fullwidth btn-bg-sand">{% trans 'Purchase' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </aside>