cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', shopping_cart_view, name='shopping_cart_view'),
    path('add/<int:pk>', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:pk>', remove_from_cart_view, name='remove_from_cart_view'),
    path('emptying_the_cart', emptying_all_of_the_products_from_the_cart, name='emptying_the_cart')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls'), name='homepage'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('shopping-cart/', include('cart.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # rosetta
    path('rosetta/', include('rosetta.urls'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', products_list_view, name='products_list_view'),
    path('<int:pk>', product_detail_view, name='product_detail_view'),
    path('<int:pk>/guest_comments', comment_system_for_guests, name='guest_comment_system'),
    path('<int:pk>/edit_comment/<int:comment_id>', edit_user_comments, name='edit_user_comments'),
    path('<int:pk>/delete_comment/<int:comment_id>', delete_user_comments, name='delete_user_comments'),
    path('<int:pk>/like_product', user_likes_on_products, name='user_likes_on_product'),
    path('<int:pk>/delete_like_product', delete_user_likes_on_products, name='delete_user_likes_on_product'),
    path('liked_products', liked_products_view, name='liked_products_view'),
]

product/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.contrib.sessions.models import Session
from ckeditor.fields import RichTextField


class ProductManager(models.Manager):  # Managers
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(product_existence=True, number_of_products__gt=0)


class CustomCommentManager(models.Manager):
    def get_queryset(self):
        return super(CustomCommentManager, self).get_queryset().filter(is_active=True, parent__isnull=True)


# Models
class Product(models.Model):
    all_available_product_classification = [
        (_('Uncategorized'), 'UN'),
        (_('Clothing and fashion'), 'CAF'),
        (_('Supermarket Items'), 'SI'),
        (_('Home Appliances'), 'HA'),
        (_('Toys'), 'TY'),
        (_('Books'), 'BO'),
    ]
    product_title = models.CharField(max_length=100, verbose_name=_('title'))
    product_description = RichTextField(blank=True, verbose_name=_('description'))
    product_datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_('datetime_created'))
    product_datetime_modified = models.DateTimeField(auto_now=True, verbose_name=_('datetime_modified'))
    product_price = models.PositiveIntegerField(default=0, verbose_name=_('price'))
    product_existence = models.BooleanField(default=True, verbose_name=_('existence'))
    product_cover = models.ImageField(upload_to='product/', default='default_product/shop_cart.jpg',
                                      verbose_name=_('cover'))
    number_of_products = models.IntegerField(default=10, verbose_name=_('numbers'))
    product_classification = models.CharField(choices=all_available_product_classification,
                                              max_length=200, default=all_available_product_classification[5],
                                              verbose_name=_('classification'))
    product_likes = models.ManyToManyField(get_user_model(), related_name='likes_on_products', blank=True, null=True,
                                            verbose_name=_('likes_on_product'))

    def __str__(self):
        return self.product_title

    def get_absolute_url(self):
        return reverse('product_detail_view', args=[self.id])

    # Product Manager
    objects = models.Manager()  # django default manager
    product_manager = ProductManager()


class UserComments(models.Model):
    PRODUCT_STARS = [
        ('5', _('perfect')),
        ('4', _('good')),
        ('3', _('normal')),
        ('2', _('bad')),
        ('1', _('Very bad')),
    ]
    text = models.TextField(verbose_name=_('comment_text'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_('comment_datetime_created'))
    datetime_modified = models.DateTimeField(auto_now=True, verbose_name=_('comment_datetime_modified'))
    is_active = models.BooleanField(default=True, verbose_name='comment_is_active')
    parent = models.ForeignKey("self", blank=True, null=True, on_delete=models.CASCADE, related_name='replies')
    rate = models.CharField(max_length=10, choices=PRODUCT_STARS, blank=True, verbose_name=_('product rate'))
    name = models.CharField(max_length=20, null=True, blank=True, verbose_name=_('name'))
    email = models.EmailField(max_length=200, null=True, blank=True, verbose_name=_('email'))

    # Comment Manager
    objects = models.Manager()  # django default manager
    custom_comment_manager = CustomCommentManager()  # our custom manager

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('product_detail_view', args=[self.product.id])


class Customer(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True)
    email = models.EmailField(max_length=200, blank=True, null=True)

product/forms.py
from .models import UserComments
from django import forms
from accounts.models import CustomUserModel
from django.contrib import messages


class UserCommentsForm(forms.ModelForm):
    class Meta:
        model = UserComments
        fields = ['text', 'rate']

    def __init__(self, *args, **kwargs):
        super(UserCommentsForm, self).__init__(*args, **kwargs)
        self.fields['rate'].required = False


class GuestCommentForm(forms.ModelForm):
    class Meta:
        model = UserComments
        fields = ['name', 'email', 'text', 'rate']

    def __init__(self, *args, **kwargs):
        super(GuestCommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['email'].required = True
        self.fields['rate'].required = False

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUserModel.objects.filter(email__iexact=email).exists() and \
                UserComments.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError('this email has been given before')
        else:
            return email

product/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Product, UserComments
from django.core.paginator import Paginator
from .forms import UserCommentsForm, GuestCommentForm
from django.contrib import messages
from django.utils.translation import gettext as _
from django.http import Http404
from cart.forms import AddToCartProductForm
from cart.cart import ShoppingCart
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required


def products_list_view(request):
    products = Product.product_manager.all().order_by('-product_datetime_created')
    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    # context
    dic = {
        'products': page_obj,
    }
    # rendering our object
    return render(request, 'product/products_list_view.html', dic)


def product_detail_view(request, pk):
    print(request.session.values())
    products = Product.product_manager.all()
    product_detail = get_object_or_404(products, pk=pk)
    comments = UserComments.custom_comment_manager.filter(product_id=pk).order_by('-datetime_created')
    # start of comment section for users
    if request.method == 'POST':
        comment_form = UserCommentsForm(request.POST)
        if comment_form.is_valid():
            # Replay section
            parent_obj = None
            # get parent comment id from hidden input
            try:
                # id integer e.g. 15
                parent_id = int(request.POST.get('parent_id'))
            except TypeError:
                parent_id = None
            # if parent_id has been submitted get parent_obj id
            if parent_id:
                parent_obj = UserComments.objects.get(id=parent_id)
                # if parent object exist
                if parent_obj:
                    # create replay comment object
                    replay_comment = comment_form.save(commit=False)
                    # assign parent_obj to replay comment
                    replay_comment.parent = parent_obj
            # End of replay section
            new_user_comment = comment_form.save(commit=False)
            new_user_comment.product = product_detail
            new_user_comment.user = request.user
            new_user_comment.save()
        messages.success(request, _('your comment saved successfully'))
        return redirect('product_detail_view', pk=pk)
    else:
        comment_form = UserCommentsForm()
    # end of comment section for users
    # check if guest session exists or not
    try:
        guest_comment_form = GuestCommentForm(initial={
                'name': request.session['guest_data']['name'],
                'email': request.session['guest_data']['email']
            })
    except KeyError:
        guest_comment_form = GuestCommentForm()
    # a method for checking the shopping cart
    shopping_cart = ShoppingCart(request)
    cart_keys = shopping_cart.shopping_cart.keys()
    is_in_the_cart = Product.objects.filter(id__in=cart_keys, pk=pk).exists()
    context = {
        'product_detail': product_detail,
        'comment_form': comment_form,
        'comments': comments,
        'guest_comment_form': guest_comment_form,
        'add_to_cart_form': AddToCartProductForm(request.POST, product_stock=product_detail.number_of_products,),
        'is_in_the_cart': is_in_the_cart,
    }
    return render(request, 'product/product_detail_view.html', context)


@require_POST
def comment_system_for_guests(request, pk):
    # initializing guest data
    request.session.get('guest_data')
    if not request.session.get('guest_data'):
        request.session['guest_data'] = {}
    guest_data = request.session['guest_data']
    product = get_object_or_404(Product.product_manager, pk=pk)
    if request.method == 'POST':
        comment_form = GuestCommentForm(request.POST)
        if comment_form.is_valid():
            cleaned_data = comment_form.cleaned_data
            new_comment = comment_form.save(commit=False)
            guest_data['name'] = cleaned_data['name']
            guest_data['email'] = cleaned_data['email']
            guest_data['session_key'] = request.session.session_key
            request.session.save()
            new_comment.product = product
            new_comment.save()
        return redirect('product_detail_view', pk=pk)
    return render(request, 'product/product_detail_view.html')


# this function should be class based view
@login_required
def edit_user_comments(request, pk, comment_id):
    current_user = request.user
    user_comments = current_user.comments.filter(is_active=True, parent__isnull=True)
    get_particular_user_comment = get_object_or_404(user_comments, pk=comment_id)
    # registering the form
    edit_form = UserCommentsForm(request.POST, instance=get_particular_user_comment)
    if request.method == 'POST':
        if edit_form.is_valid():
            edit_form.save()
        messages.success(request, _('your comment changed successfully'))
        return redirect('product_detail_view', pk=pk)
    # dic for context
    dic = {
        'edit_comment_form': edit_form
    }
    return render(request, 'product/edit_product_comments.html', dic)


# this function should be class based view
@login_required
def delete_user_comments(request, pk, comment_id):
    # product detail for redirect section in template, UserComment get_absolute_url does not work correctly
    products = Product.objects.all().filter(product_existence=True)
    product_detail = get_object_or_404(products, pk=pk)
    user = request.user
    user_comments = user.comments.filter(is_active=True, parent__isnull=True)
    getting_particular_user_comment = get_object_or_404(user_comments, pk=comment_id)
    if request.method == 'POST':
        getting_particular_user_comment.delete()
        messages.success(request, _('your comment deleted successfully'))
        return redirect('product_detail_view', pk)

    # dic for context
    dic = {
        'product_detail': product_detail
    }
    return render(request, 'product/delete_product_comments.html', dic)


@login_required
def user_likes_on_products(request, pk):
    product = get_object_or_404(Product.product_manager, pk=pk)
    current_user = request.user
    if current_user.is_authenticated:
        if current_user not in product.product_likes.all():
            product.product_likes.add(current_user)
            return redirect('products_list_view')
    else:
        raise Http404()


@login_required
def delete_user_likes_on_products(request, pk):
    product = get_object_or_404(Product.product_manager, pk=pk)
    current_user = request.user
    if current_user.is_authenticated:
        if current_user in product.product_likes.all():
            product.product_likes.remove(current_user)
            return redirect('products_list_view')
    else:
        raise Http404()


@login_required
def liked_products_view(request):
    current_user = request.user
    user_liked_products = current_user.likes_on_products.all()
    dic = {
        'user_liked_products': user_liked_products
    }
    return render(request, 'product/liked_products.html', dic)

product/templates/product/delete_product_comments.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/delete_card.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-4 offset-sm-3 offset-md-4">
                <div class="info-card info-card--danger bg-white text-center mb-4 rounded-lg">
                    <div class="info-card_icon mx-auto mb-4 d-flex justify-content-center align-items-center position-relative">
                        <i class="fa fa-trash"></i>
                    </div>
                    <h2 class="mb-4">Delete action</h2>
                    <div class="mb-4">
                        <h4>ایا از حذف این نظر اطمینان دارید؟</h4>
                        <div class="buttons_positions">
                             <div class="button_delete">
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit" onclick="this.disabled=true;this.form.submit();"
                                    >حذف نظر</button>
                                </form>
                            </div>
                            <div class="button_cancel">
                                 <a href="{% url 'product_detail_view' product_detail.id %}"><button class="btn btn-secondary">لغو</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

product/templates/product/edit_product_comments.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
         <form method="post">
            {% csrf_token %}
            {{ edit_comment_form|crispy }}
            <button type="submit" value="yes" onclick="this.disabled=true;this.form.submit();" class="mt-3">ارسال مجدد</button>
        </form>
    </div>
{% endblock content %}

product/templates/product/products_list_view.html
{% extends '_base.html' %}
{% load i18n %}
{% load english_to_persian_translate_tags %}
{% load humanize %}

{% block content %}
    <body>

    <!-- Preloader Start -->
{#    <div class="ShoppingYar-preloader active">#}
{#        <div class="ShoppingYar-preloader-inner h-100 d-flex align-items-center justify-content-center">#}
{#            <div class="ShoppingYar-child ShoppingYar-bounce1"></div>#}
{#            <div class="ShoppingYar-child ShoppingYar-bounce2"></div>#}
{#            <div class="ShoppingYar-child zuka-bounce3"></div>#}
{#        </div>#}
{#    </div>#}
    <!-- Preloader End -->


        {% include 'top_header.html' with main_header='Products' %}
        <!-- Main Content Wrapper Start -->
        <div  class="main-content-wrapper container-fluid">
            <div class="shop-page-wrapper shop-fullwidth">
                <div class="container">
                    <div class="row mb--50">
                        <div class="col-12">
                            <div class="shop-toolbar">
                                <div class="container row align-items-center">
                                    <div class="col-lg-12 mb-md--50 mb-xs--10">
                                        <div class="shop-toolbar__left d-flex align-items-sm-center align-items-start flex-sm-row flex-column">
                                            <p class="product-pages">نمایش ۱-۲۰ از ۴۹</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container-fluid shop-products">
                    <div class="row">
                        <div class="col-12">
                            <div class="tab-content" id="product-tab-content">
                                <div class="tab-pane fade show active" id="nav-all">
                                    <div class="row xxl-block-grid-6 grid-space-20">
                                        {% for product in products %}
                                            <div class="col-xl-3 col-md-4 col-sm-6 mb--50">
                                                <div class="ShoppingYar-product">
                                                    <div class="product-inner">
                                                        <figure class="product-image">
                                                            <a href="{{ product.get_absolute_url }}">
                                                                <img src="{{ product.product_cover.url }}" alt="Products">
                                                            </a>
                                                            <div class="ShoppingYar-product-action">
                                                                {% if user.is_authenticated %}
                                                                    {% if user not in product.product_likes.all %}
                                                                        <div class="product-action d-flex">
                                                                            <a href="{% url 'user_likes_on_product' product.id %}" class="action-btn">
                                                                                <i class="flaticon flaticon-like"></i>
                                                                            </a>
                                                                        </div>
                                                                    {% else %}
                                                                         <div class="product-action d-flex">
                                                                            <a href="{% url 'delete_user_likes_on_product' product.id %}" class="action-btn">
                                                                                <i class="fas fa-heart"></i>
                                                                            </a>
                                                                        </div>
                                                                    {% endif %}
                                                                {% endif %}
                                                            </div>
                                                        </figure>
                                                        <div class="product-info">
                                                            <h3 class="product-title mb--15">
                                                                <a href="{{ product.get_absolute_url }}">{{ product.product_title }}</a>
                                                            </h3>
                                                            <div class="product-price-wrapper mb--30">
                                                                <span class="money">{{ product.product_price|intcomma:False|translate_number }} تومان</span>
                                                            </div>
                                                            <div class="product-price-wrapper mb--30">
                                                                <span class="money">{{ product.product_classification }}</span>
                                                            </div>
                                                            <a href="{% url 'cart:shopping_cart_view' %}"
                                                               class="btn btn-small btn-bg-sand btn-color-dark px-3">
                                                                اضافه کردن به سبد خرید</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <nav class="pagination-wrap mt--35 mt-md--25 pb-5">
                                <ul class="pagination">
                                    {% if products.has_next %}
                                         <li><a href="?page={{ products.next_page_number }}" class="next page-number">
                                             <i class="fa fa-angle-double-left"></i></a></li>
                                    {% endif %}
                                    {% if products.has_previous %}
                                        <li><a href="?page={{ products.previous_page_number }}" class="prev page-number">
                                            <i class="fa fa-angle-double-right"></i></a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->
        <!-- Search form Popup Start -->
        <div class="searchform__popup" id="searchForm">
            <a href="#" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="searchform__body">
                <p>در باکس زیر عبارت خود را وارد کنید</p>
                <form class="searchform">
                    <input type="text" name="popup-search" id="popup-search" class="searchform__input" placeholder="جستجو در بین محصولات...">
                    <button type="submit" class="searchform__submit"><i class="flaticon flaticon-magnifying-glass-icon"></i></button>
                </form>
            </div>
        </div>
        <!-- Search form Popup End -->

        <!-- Mini Cart Start -->
       {% include 'cart/shopping_cart_sidebar.html' %}
        <!-- Mini Cart End -->

        <!-- Global Overlay Start -->
        <div class="ShoppingYar-global-overlay"></div>
        <!-- Global Overlay End -->

    </div>
    <!-- Main Wrapper End -->


    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="assets/js/vendor.js"></script>

    <!-- Main JS -->
    <script src="assets/js/main.js"></script>

</body>
{% endblock content %}